# -*- coding: utf-8 -*-
"""Python_Lesson_Dictionaries_Classes_Objects_FM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JKkX0hNLymwfufHNOXT8Nj8ZWbXpObw2
"""

'''

#XXXXXX  LEZIONE COME USARE IL DIZIONARIO PYTHON  XXXXXX

'''

d = dict()
#codice base per creare un dizionario
# d = dict('George':24, 'Tom':32)

d = {}
#codice semplificato per creare un dizionario

d['George'] = 24
d['Tom'] = 32
d['Jenny'] = 16
#codice base per aggiungere elementi (keys) al nostro dizionario creato
#generalmente le keys (elementi del dizionario) sono stringhe o numeri

d['George']
#una volta che inseriamo elementi (keys) nel nostro dizionario, possiamo rievocarli printando l`elemento.

#result: 24

d[10] = 100
d[10]
#esempio di key fatta da numeri

#result: 100

for key, value in d.items():
  print('key:')
  print(key)
  print('value:')
  print(value)
  print('')
#codice per richiamare gli elementi (keys) del dizionario. d['George'] = 24.
#in questo caso con 'key' richiamiamo il primo elemento, con 'value' l`lelemento assegnato

#result:
#key:
#George
#value:
#24

#key:
#Tom
#value:
#32

#key:
#Jenny
#value:
#16

#key:
#10
#value:
#100


'''

#XXXXXX  LEZIONE CLASSI ED OGGETTI PYTHON  XXXXXX

'''


class Robot:
  def introduce_self(self):
    print('My name is ' + self.name) #this is Java
    print('My color is ' + self.color)
    print('My weight is ' + self.weight)
#codice per creare una definizione, in questo caso 'introduce_self(self)' per richiamare i vari parametri.

r1 = Robot()
r1.name = 'Tom'
r1.color = 'red'
r1.weight = '30'

r2 = Robot()
r2.name = 'Jerry'
r2.color = 'blue'
r2.weight = '40'

r1.introduce_self()
r2.introduce_self()

#result:
#My name is Tom
#My color is red
#My weight is 30
#My name is Jerry
#My color is blue
#My weight is 40

'''
#XXXX ALTRO MODO DI SCRIVERE IL CODICE USANDO 'def __init__()' XXXX
'''

class Robot:
  def __init__(self, name, color, weight):
#codice per creare un costrutto personalizzato con 'def __init__()'
    self.name = name
    self.color = color
    self.weight = weight
#codice base per creare una classe. In questo caso 'Robot'
  def introduce_self(self):
    print('My name is ' + self.name) #this is Java
    print('My color is ' + self.color)
    print('My weight is ' + self.weight)

r1 = Robot('Tom', 'red', '30')
r2 = Robot('Jerry', 'blue', '40')

r1.introduce_self()
r2.introduce_self()

#result:
#My name is Tom
#My color is red
#My weight is 30
#My name is Jerry
#My color is blue
#My weight is 40


'''
#XXXXX  PARTE DUE  XXXXX
'''


class Robot:
  def __init__(self, name, color, weight):
#codice per creare un costrutto personalizzato con 'def __init__()'
    self.name = name
    self.color = color
    self.weight = weight
#codice base per creare una classe. In questo caso 'Robot'
  def introduce_rob(self):
    print('My name is ' + self.name) #this is Java
    print('My color is ' + self.color)
    print('My weight is ' + self.weight)

class Person:
  def __init__(self, name, personality, age, writing_hand ):
    self.name = name
    self.personality = personality
    self.age = age
    self.writing_hand = writing_hand
  def introduce_self(self):
    print('My name is ' + self.name) #this is Java
    print('My personality is ' + self.personality)
    print('I am ' + self.age)
    print('Right hand: ' + self.writing_hand)
  def right_hand(self):
    self.writing_hand = True
  def left_hand(self):
    self.writing_hand = False

r1 = Robot('Tom', 'red', '30')
r2 = Robot('Jerry', 'blue', '40')
p1 = Person('Alice', 'aggressive', '15', 'False')
p2 = Person('Becky', 'talkative', '12', 'True')

People = p1.name, p2.name
Robots = r1.name, r2.name

print(People)
print(Robots)

#result:
#('Alice', 'Becky')
#('Tom', 'Jerry')

#dobbiamo mostrare che una persona possiede un robot
p1.robot_owned = r2
p2.robot_owned = r1

p1.introduce_self()
print('')
print('This is my robot:')
print('')
p1.robot_owned.introduce_rob()
print('')
p2.introduce_self()
print('')
print('This is my robot:')
print('')
p2.robot_owned.introduce_rob()

#result:

#My name is Alice
#My personality is aggressive
#I am 15
#Right hand: False

#This is my robot:

#My name is Jerry
#My color is blue
#My weight is 40

#My name is Becky
#My personality is talkative
#I am 12
#Right hand: True

#This is my robot:

#My name is Tom
#My color is red
#My weight is 30